<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NoteRecall_Backend</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<!-- Core API / Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

		<!-- Authentication -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />

		<!-- Entity Framework (Design-time only) -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- AutoMapper -->
		<PackageReference Include="AutoMapper" Version="16.1.1" />

		<!-- Serilog -->
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />

		<!-- JWT low-level handling (optional but fine) -->
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NoteRecall-Application\NoteRecall-Application.csproj" />
    <ProjectReference Include="..\NoteRecall-Infrastructure\NoteRecall-Infrastructure.csproj" />
  </ItemGroup>

</Project>
