<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NoteRecall_Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="ServiceImplementation\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoteRecall-Core\NoteRecall-Core.csproj" />
  </ItemGroup>

</Project>
